apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app.kubernetes.io/name: redis-operator
  app.kubernetes.io/instance: redis-operator

components:
  - ../../components/rbac-full/

resources:
  - ../../base/

patchesStrategicMerge:
  - deployment.yaml
